data_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('dataquestions/', include('dataquestions.urls')),
    path('admin/', admin.site.urls),
]

dataquestions/urls.py
from django.urls import path

from . import views

app_name = 'dataquestions'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.plot_data, name='plot_data'),
]

dataquestions/models.py
from django.db import models


class Matches(models.Model):
    id = models.IntegerField(primary_key=True)
    season = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    date = models.DateField()
    team1 = models.CharField(max_length=255)
    team2 = models.CharField(max_length=255)
    toss_winner = models.CharField(max_length=255)
    toss_decision = models.CharField(max_length=255)
    result = models.CharField(max_length=255)
    dl_applied = models.IntegerField(default=0)
    winner = models.CharField(max_length=255)
    win_by_runs = models.IntegerField()
    win_by_wickets = models.IntegerField()
    player_of_match = models.CharField(max_length=255)
    venue = models.CharField(max_length=255)
    umpire1 = models.CharField(max_length=255)
    umpire2 = models.CharField(max_length=255)
    umpire3 = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"match id = {self.id} season = {self.season}"


class Deliveries(models.Model):
    match = models.ForeignKey(Matches, on_delete=models.CASCADE)
    inning = models.IntegerField()
    batting_team = models.CharField(max_length=255)
    bowling_team = models.CharField(max_length=255)
    over = models.IntegerField()
    ball = models.IntegerField()
    batsman = models.CharField(max_length=255)
    non_striker = models.CharField(max_length=255)
    bowler = models.CharField(max_length=255)
    is_super_over = models.IntegerField()
    wide_runs = models.IntegerField()
    bye_runs = models.IntegerField()
    legbye_runs = models.IntegerField()
    noball_runs = models.IntegerField()
    penalty_runs = models.IntegerField()
    batsman_runs = models.IntegerField()
    extra_runs = models.IntegerField()
    total_runs = models.IntegerField()
    player_dismissed = models.CharField(max_length=255)
    dismissal_kind = models.CharField(max_length=255)
    fielder = models.CharField(max_length=255)

    def __str__(self):
        return f"ball id = {self.pk} match_id = {self.match}"

dataquestions/views.py
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from .question_id_decision_map import DECISION_MAP


CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)


@cache_page(CACHE_TTL)
def index(request):
    return render(request, 'dataquestions/index.html')


@cache_page(CACHE_TTL)
def plot_data(request, question_id):
    execute_query = DECISION_MAP[question_id]
    query_set = execute_query()
    return render(request, 'dataquestions/plot_data.html', {'query_set': query_set,
                                                            'question_id': question_id, })

dataquestions/templates/dataquestions/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Data Project</title>
  </head>
  <body>
    <h1>Django Data Project</h1>
    <ul>
      <li>Question 1: Plot the number of matches played per year of all the years in IPL.&nbsp;<a href="{% url 'dataquestions:plot_data' question_id=1 %}">Plot chart</a></li>
      <li>Question 2: Plot a stacked bar chart of matches won of all teams over all the years of IPL.&nbsp;<a href="{% url 'dataquestions:plot_data' question_id=2 %}">Plot chart</a></li>
      <li>Question 3: For the year 2016 plot the extra runs conceded per team.&nbsp;<a href="{% url 'dataquestions:plot_data' question_id=3 %}">Plot chart</a></li>
      <li>Question 4: For the year 2015 plot the top economical bowlers.&nbsp;<a href="{% url 'dataquestions:plot_data' question_id=4 %}">Plot chart</a></li>
    </ul>
  </body>
</html>

dataquestions/templates/dataquestions/plot_data.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Plot Question {{ question_id }}</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
  </head>
  <body>

    <!-- Plot question 1 -->
    {% if question_id == 1 %}
      <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

      <script type="text/javascript">

        Highcharts.chart('container', {
          chart: {
              type: 'column'
          },
          title: {
              text: 'Matches per year'
          },
          subtitle: {
              text: 'Source: IPL dataset'
          },
          xAxis: {
              categories: [
                  {% for season in query_set %}
                    '{{ season.season }}',
                  {% endfor %}
              ],
              crosshair: true,
              title: {
                text: 'Seasons'
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Matches'
              }
          },
          tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                  '<td style="padding:0"><b>{point.y:.1f} </b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: [{
              name: 'Matches',
              data: [
                {% for season in query_set %}
                  {{ season.total }},
                {% endfor %}
              ]
          },]
        });
      </script>

    <!-- Plot question 2 -->
    {% elif question_id == 2 %}
      <div id="container" style="min-width: 310px; height: 500px; margin: 0 auto"></div>
      <script type="text/javascript">

        Highcharts.chart('container', {
          chart: {
              type: 'column'
          },
          title: {
              text: 'Matches won by all teams over all the seasons of IPL'
          },
          xAxis: {
              categories: ['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',],
              title: {
                text: 'Seasons'
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Total matches'
              },
              stackLabels: {
                  enabled: true,
                  style: {
                      fontWeight: 'bold',
                      color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                  }
              }
          },
          legend: {
              align: 'center',
              x: 0,
              verticalAlign: 'bottom',
              y: 10,
              floating: true,
              backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
              borderColor: '#CCC',
              borderWidth: 1,
              shadow: false
          },
          tooltip: {
              headerFormat: '<b>{point.x}</b><br/>',
              pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
          },
          plotOptions: {
              column: {
                  stacking: 'normal',
                  dataLabels: {
                      enabled: false,
                      color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                  }
              }
          },
          series: [
            {% for team, matches in query_set.items %}
              {
                name: '{{ team }}',
                data: [
                  {% for _, wins in matches.items %}
                    {{ wins }},
                  {% endfor %}
                ]
              },
            {% endfor %}
          ]
        });
      </script>

    <!-- Plot Question 3 -->
    {% elif question_id == 3 %}
      <div id="container" style="min-width: 310px; height: 500px; margin: 0 auto"></div>

      <script type="text/javascript">

        Highcharts.chart('container', {
          chart: {
              type: 'column'
          },
          title: {
              text: 'Extra runs conceded per team in 2016 season'
          },
          subtitle: {
              text: 'Source: IPL dataset'
          },
          xAxis: {
              categories: [
                  {% for team in query_set %}
                    '{{ team.bowling_team }}',
                  {% endfor %}
              ],
              crosshair: true,
              title: {
                text: 'Teams'
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Total extra runs'
              }
          },
          tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                  '<td style="padding:0"><b>{point.y:.1f} </b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: [{
              name: 'Runs',
              data: [
                {% for team in query_set %}
                  {{ team.runs }},
                {% endfor %}
              ]
          },]
        });
      </script>

    <!-- Plot Question 4 -->
    {% elif question_id == 4 %}
      <div id="container" style="min-width: 310px; height: 500px; margin: 0 auto"></div>

      <script type="text/javascript">

        Highcharts.chart('container', {
          chart: {
              type: 'column'
          },
          title: {
              text: 'Top economical bowlers of 2015 season'
          },
          subtitle: {
              text: 'Source: IPL dataset'
          },
          xAxis: {
              categories: [
                  {% for bowler in query_set %}
                    '{{ bowler.bowler }}',
                  {% endfor %}
              ],
              crosshair: true,
              title: {
                text: 'Bowlers'
              }
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Bowling economy'
              }
          },
          tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                  '<td style="padding:0"><b>{point.y:.1f} </b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: [{
              name: 'Economy',
              data: [
                {% for bowler in query_set %}
                  {{ bowler.avg }},
                {% endfor %}
              ]
          },]
        });
      </script>

    {% endif %}


  </body>
</html>